package com.renlz.jiyun.greeknews.myenums;

/**
 * Created by Administrator on 2018/12/26.
 */

public enum EnumApi {
    NEWSETNEW,
    BEFORELIST,
    THEMELIST,
    THEMECHILDLIST,
    SECTIONLIST,
    HOTLIST,
    DETAILEXTRAINFO,
    LONGCOMMENTINFO,
    SHORTCONMMENTINFO,
    WXNEWS,
    GANHUOS,
    RANDOMSISTER,
    COUNTLIST,
    SJZHNEWSTYPE,
    SJZHNEWS,
    V2EXTYPE,
    V2EXTHEME,
    V2EXTOP,
    V2RXLIST,
    WEIXINSEARCH,
    GANHUOSEARCH,
    SISTERLIST,
    ZHUANLANLIST,
    ZHUANLANINFO,
    SHUJUZHIHUIINFO,
}
